# src/infrastructure/database/oracle_db.py

import oracledb

def get_database_connection():
    dsn = oracledb.makedsn("orion.javeriana.edu.co", 1521, service_name="LAB")
    return oracledb.connect(user="is819901", password="d5MryKS66PIkkDh", dsn=dsn)

def initialize_database():
    try:
        connection = get_database_connection()
        cursor = connection.cursor()

        # Eliminar tabla si existe
        cursor.execute("""
            BEGIN
                EXECUTE IMMEDIATE 'DROP TABLE USER_ENTITY';
            EXCEPTION
                WHEN OTHERS THEN
                    IF SQLCODE != -942 THEN
                        RAISE;
                    END IF;
            END;
        """)

        # Crear tabla
        cursor.execute("""
            BEGIN
                EXECUTE IMMEDIATE 'CREATE TABLE USER_ENTITY (
                    ID INT GENERATED BY DEFAULT ON NULL AS IDENTITY,
                    NAME VARCHAR2(100),
                    EMAIL VARCHAR2(100),
                    GENDER VARCHAR2(10),
                    STATUS VARCHAR2(10),
                    CONSTRAINT user_entity_pk PRIMARY KEY (ID)
                )';
            END;
        """)
        print("La tabla User fue creada exitosamente.")

        # Reiniciar secuencia
        cursor.execute("DROP SEQUENCE USER_ENTITY_SEQ")
        cursor.execute("CREATE SEQUENCE USER_ENTITY_SEQ START WITH 1 INCREMENT BY 1")

        print("La secuencia USER_ENTITY_SEQ fue reiniciada exitosamente.")
        
    except oracledb.Error as e:
        print("Error occurred:", e)
    finally:
        cursor.close()
        connection.close()
